name: auto deploy
on:
  push:
    branches:
      - master #2020年10月后github新建仓库默认分支改为main，注意更改
  release:
    types:
    - published

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 检查分支
        uses: actions/checkout@v2
        with:
          ref: master #2020年10月后github新建仓库默认分支改为main，注意更改

      - name: 安装 Node
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
          cache: 'npm'

      - name: 安装依赖
        run: |
          npm install

      - name: 构建
        run: |
          npm run build

  depoly: 
    runs-on: ubuntu-latest
    steps:
      # 打包镜像推送到阿里云容器镜像服务
      - name: 构建容器镜像
        run: |
          docker login --username=${{ secrets.DOCKER_USERNAME }}  registry.cn-hangzhou.aliyuncs.com --password-stdin=${{ secrets.DOCKER_PASSWORD }}
          docker build -t lx-music:latest .
          docker tag lx-music registry.cn-hangzhou.aliyuncs.com/lixin94/lx-music:latest
          docker push registry.cn-hangzhou.aliyuncs.com/lixin94/lx-music:latest
      # - name: ssh docker login # 使用appleboy/ssh-action@master登录服务器执行拉取镜像脚本，服务器ip、用户名、密码配置方式同容器镜像服务配置方式一样
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.HOST }}
      #     key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     username: ${{ secrets.USERNAME }}
      #     script: cd ~ && sh lx-music-deploy.sh ${{ secrets.DOCKER_USERNAME }} ${{ secrets.DOCKER_PASSWORD }}
