name: auto deploy
on:
  push:
    branches:
      - master #2020年10月后github新建仓库默认分支改为main，注意更改
  release:
    types:
    - published

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: 检查分支
        uses: actions/checkout@v2
        with:
          ref: master #2020年10月后github新建仓库默认分支改为main，注意更改

      - name: 安装 Node
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
          cache: 'npm'

      - name: 安装依赖
        run: |
          npm install

      - name: 构建
        run: |
          npm run build

      - name: 发布到GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
